---
# the hob is created first then the deployment gets started
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: cronjob-cassandra-schema
    app.kubernetes.io/instance: with-cassandra
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: with-cassandra-cassandra-schema-job
    app.kubernetes.io/part-of: jaeger
  name: with-cassandra-cassandra-schema-job
  namespace: default
spec:
  activeDeadlineSeconds: 180
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: c2c037b4-3d60-4298-9aec-3a6575bc6c67
  suspend: false
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        prometheus.io/scrape: "false"
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: c2c037b4-3d60-4298-9aec-3a6575bc6c67
        batch.kubernetes.io/job-name: with-cassandra-cassandra-schema-job
        controller-uid: c2c037b4-3d60-4298-9aec-3a6575bc6c67
        job-name: with-cassandra-cassandra-schema-job
    spec:
      activeDeadlineSeconds: 320
      containers:
      - env:
        - name: MODE
          value: test
        - name: DATACENTER
          value: datacenter3
        - name: CQLSH_HOST
          value: cassandra.default.svc
        - name: CQLSH_PORT
          value: "9042"
        - name: KEYSPACE
          value: jaeger_v1_datacenter3
        - name: CASSANDRA_USERNAME
        - name: CASSANDRA_PASSWORD
        - name: TRACE_TTL
          value: "172800"
        image: jaegertracing/jaeger-cassandra-schema:1.54.0
        imagePullPolicy: IfNotPresent
        name: with-cassandra-cassandra-schema-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: with-cassandra
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: with-cassandra
    app.kubernetes.io/part-of: jaeger
  name: with-cassandra
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: with-cassandra
      app.kubernetes.io/managed-by: jaeger-operator
      app.kubernetes.io/name: with-cassandra
      app.kubernetes.io/part-of: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        prometheus.io/port: "14269"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: jaeger
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/instance: with-cassandra
        app.kubernetes.io/managed-by: jaeger-operator
        app.kubernetes.io/name: with-cassandra
        app.kubernetes.io/part-of: jaeger
    spec:
      containers:
      - args:
        - --cassandra.keyspace=jaeger_v1_datacenter3
        - --cassandra.servers=cassandra.default.svc
        - --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
        env:
        - name: SPAN_STORAGE_TYPE
          value: cassandra
        - name: METRICS_STORAGE_TYPE
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: :9411
        - name: JAEGER_DISABLED
          value: "false"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        image: jaegertracing/all-in-one:1.54.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 14269
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: jaeger
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
          protocol: TCP
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        - containerPort: 14267
          name: c-tchan-trft
          protocol: TCP
        - containerPort: 14268
          name: c-binary-trft
          protocol: TCP
        - containerPort: 16685
          name: grpc-query
          protocol: TCP
        - containerPort: 16686
          name: query
          protocol: TCP
        - containerPort: 14269
          name: admin-http
          protocol: TCP
        - containerPort: 14250
          name: grpc
          protocol: TCP
        - containerPort: 4317
          name: grpc-otlp
          protocol: TCP
        - containerPort: 4318
          name: http-otlp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 14269
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/jaeger/sampling
          name: with-cassandra-sampling-configuration-volume
          readOnly: true
      serviceAccount: with-cassandra
      serviceAccountName: with-cassandra
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: sampling
            path: sampling.json
          name: with-cassandra-sampling-configuration  # it is created by the job
        name: with-cassandra-sampling-configuration-volume
