---
apiVersion: v1
kind: Namespace
metadata:
  name:  jaeger
---
# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  namespace: jaeger
data:
  memory.yaml: |-
    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: [batch]
          exporters: [jaeger_storage_exporter]

    extensions:
      jaeger_query:
        trace_storage: memstore

      jaeger_storage:
        memory:
          memstore:
            max_traces: 100000

    receivers:
      otlp:
        protocols:
          grpc:
          http:

      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:

      zipkin:

    processors:
      batch:

    exporters:
      jaeger_storage_exporter:
        trace_storage: memstore

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  jaeger-all-in-one
  namespace: jaeger
  labels:
    app:  jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  replicas: 1
  template:
    metadata:
      labels:
        app:  jaeger
    spec:
      containers:
      - name:  jaeger
        image:  jaegertracing/jaeger:latest
        args: ['--config', '/configs/memory.yaml']
        
        volumeMounts:
        - name: config
          mountPath: /configs

        ports:
        - containerPort: 5775
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 5778
        - containerPort: 16686
        - containerPort: 14268
        - containerPort: 9411
      volumes:
        - name: config
          configMap:
            name: jaeger-configuration
            items:
            - key: "memory.yaml"
              path: "memory.yaml"
---

# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: jaeger
spec:
  selector:
    app: jaeger
  type: ClusterIP
  ports:
  - name: ui
    protocol: TCP
    port: 16686
    targetPort: 16686
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: conn
---

